### PR TITLE
Mobile friendly

### PR DESCRIPTION
**Pull request by kvothe1387**
zodiac card page is now responsive

### CODE REVIEW

**Review by jesseunderwood — COMMENTED** [review]
everything looks good

**Review by jesseunderwood — COMMENTED** [review]
everything looks good

**Review by soupmcnally — COMMENTED** [review]
looks good to me, player

**Comment by jesseunderwood** [comment]
everything looks good

**Review by soupmcnally — APPROVED** [review]
i approve this business merger

**Pull request merged**
